#!/usr/bin/sh
set -eu

if [ -z "${ANDROID_NDK_HOME:-}" ]; then
    echo "Error: Env Variable ANDROID_NDK_HOME is not set."
    exit 1
fi

if [ -z "${GITHUB_REF_NAME:-}" ] && [ -z "${VERSION:-}" ]; then
    echo "Error: Env Variable GITHUB_REF_NAME or VERSION is not set."
    exit 1
fi

rm -rf blake3-kmp/src/jvmMain/resources/jni
rm -rf blake3-kmp/src/androidMain/jniLibs
rm -rf blake3-kmp-android-test/src/jvmMain/resources/jni
rm -rf blake3-kmp-android-test/src/androidMain/jniLibs
rm -rf blake3-ffm/src/main/resources/jni

mkdir -p blake3-kmp/src/jvmMain/resources/jni
mkdir -p blake3-kmp/src/androidMain/jniLibs
mkdir -p blake3-kmp-android-test/src/jvmMain/resources/jni
mkdir -p blake3-kmp-android-test/src/androidMain/jniLibs
mkdir -p blake3-ffm/src/main/resources/jni

cd blake3-kmp
zig build android -p src/androidMain/jniLibs
zig build android-test -p ../blake3-kmp-android-test/src/androidMain/jniLibs
zig build jvm -p src/jvmMain/resources/jni
cd ..

cp -R blake3-kmp/src/jvmMain/resources/jni/. blake3-kmp-android-test/src/jvmMain/resources/jni/
cp -R blake3-kmp/src/jvmMain/resources/jni/. blake3-ffm/src/main/resources/jni/

find blake3-kmp/src/jvmMain/resources/jni blake3-kmp-android-test/src/jvmMain/resources/jni blake3-ffm/src/main/resources/jni -name "*.pdb" -type f -delete
find blake3-kmp/src/jvmMain/resources/jni blake3-kmp-android-test/src/jvmMain/resources/jni blake3-ffm/src/main/resources/jni -name "*.lib" -type f -delete

printf '\n===== standard Android JNI (no x86_64) =====\n'
ls -lRh blake3-kmp/src/androidMain/jniLibs
printf '\n===== Android test JNI (x86_64 only) =====\n'
ls -lRh blake3-kmp-android-test/src/androidMain/jniLibs
printf '\n===== desktop JVM JNI =====\n'
ls -lRh blake3-kmp/src/jvmMain/resources/jni
printf '\n---------- zig build is done ----------\n'

./gradlew publishToMavenLocal
