name: build

on:
  pull_request: { }
  workflow_dispatch: { }
  push:
    branches:
      - 'main'
    tags:
      - '**'

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  build-binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: mlugg/setup-zig@v2
        with:
          version: 0.16.0

      - run: |
          zig build jvm -p src/jvmMain/resources/jni
          zig build android -p src/androidMain/jniLibs
        working-directory: blake3-kmp

      - run: |
          find src/jvmMain/resources/jni -name "*.pdb" -type f -delete
          find src/jvmMain/resources/jni -name "*.lib" -type f -delete
          ls -lRh src/jvmMain/resources/jni
          ls -lRh src/androidMain/jniLibs
        working-directory: blake3-kmp

      - uses: actions/upload-artifact@v7
        with:
          name: blake3-kmp-jvm-binary
          path: blake3-kmp/src/jvmMain/resources/jni
          if-no-files-found: error

      - uses: actions/upload-artifact@v7
        with:
          name: blake3-kmp-android-binary
          path: blake3-kmp/src/androidMain/jniLibs
          if-no-files-found: error

  static-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Ensure Android SDK location property
        run: |
          if [ -d "$ANDROID_HOME" ]; then
            echo "sdk.dir=$ANDROID_HOME" > local.properties
          elif [ -d "$ANDROID_SDK_ROOT" ]; then
            echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          else
            mkdir -p /tmp/android-sdk
            echo "sdk.dir=/tmp/android-sdk" > local.properties
          fi

      - name: Static checks
        run: ./gradlew spotlessCheck check -x testAndroid -x testAndroidHostTest -x jvmTest -x androidConnectedCheck

  binary-test-distribution:
    runs-on: ubuntu-latest
    needs:
      - build-binaries
      - static-checks
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/download-artifact@v7
        with:
          name: blake3-kmp-jvm-binary
          path: blake3-kmp/src/jvmMain/resources/jni

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - run: ./gradlew :blake3-kmp:installJvmTestDistribution

      - uses: actions/upload-artifact@v7
        with:
          name: blake3-kmp-binary-tests
          path: blake3-kmp/build/install/jvmTest
          if-no-files-found: error

  jvm-platform-test:
    needs:
      - binary-test-distribution
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macOS-15-intel
            native-target: macosX64
          - os: macOS-15
            native-target: macosArm64
          - os: ubuntu-24.04
            native-target: linuxX64
          - os: ubuntu-24.04-arm
            native-target: linuxArm64
          - os: windows-2025
            native-target: mingwX64
          - os: windows-11-arm
            native-target: mingwArm64
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/download-artifact@v7
        with:
          name: blake3-kmp-binary-tests

      - name: Run JVM tests
        run: |
          chmod +x bin/blake3-kmp-test || true
          bin/blake3-kmp-test

  android-test:
    needs:
      - binary-test-distribution
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            api-level: 27
            arch: x86
          - os: ubuntu-latest
            api-level: 37
            arch: x86_64
          - os: macOS-15
            api-level: 27
            arch: arm64-v8a
          - os: macOS-15
            api-level: 37
            arch: arm64-v8a
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/download-artifact@v7
        with:
          name: blake3-kmp-android-binary
          path: blake3-kmp/src/androidMain/jniLibs

      - run: ls -lRh src/androidMain/jniLibs
        working-directory: blake3-kmp

      - name: Enable KVM on Linux (for Android Emulator)
        if: runner.os == 'Linux'
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: AVD cache
        uses: actions/cache@v6
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          emulator-boot-timeout: 20000
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: run android test
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ matrix.arch }}
          emulator-boot-timeout: 20000
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew assembleAndroidTest connectedAndroidDeviceTest

      - uses: actions/upload-artifact@v7
        with:
          name: test-report
          path: |
            **/build/reports/tests/**
            **/build/reports/androidTests/connected/**
          retention-days: 1

  publish:
    needs:
      - jvm-platform-test
      - android-test
      - static-checks
    runs-on: ubuntu-latest
    if: always() && !cancelled()
    steps:
      - name: Check
        run: |
          results=$(tr -d '\n' <<< '${{ toJSON(needs.*.result) }}')
          if ! grep -q -v -E '(failure|cancelled)' <<< "$results"; then
            echo "One or more required jobs failed"
            exit 1
          fi

      - uses: actions/checkout@v7
        if: startsWith(github.ref, 'refs/tags/')
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'

      - uses: actions/download-artifact@v7
        with:
          name: blake3-kmp-jvm-binary
          path: blake3-kmp/src/jvmMain/resources/jni

      - uses: actions/download-artifact@v7
        with:
          name: blake3-kmp-android-binary
          path: blake3-kmp/src/androidMain/jniLibs

      - run: ./gradlew publishToMavenLocal

      - uses: actions/upload-artifact@v7
        with:
          name: blake3-kmp-published-library
          path: ~/.m2/repository/com/akhsaul/blake3
          if-no-files-found: error
